ebusiness/urls.py
#from django.conf.urls import url
from django.urls import re_path
from django.contrib import admin
from goods import views	
#from django.views import static
from django.conf.urls.static import static
from . import settings
from django.conf import settings
#from django.views.static import serve

urlpatterns = [
	re_path(r'^$', views.index),
	re_path(r'^index/$', views.index),
	re_path(r'^good_view/$', views.index),
	re_path(r'^admin/', admin.site.urls),
	re_path(r'^logout/$', views.logout),
	re_path(r'^register/$', views.register),
	re_path(r'^user_info/$', views.user_info),
	re_path(r'^login_action/$', views.login_action),
	re_path(r'^search_name/$', views.search_name),
        re_path(r'^change_password/$', views.change_password),
	re_path(r'^goods_view/$', views.goods_view),
	re_path(r'^view_goods/(?P<good_id>[0-9]+)/$', views.view_goods),
	re_path(r'^view_chart/$', views.view_chart),
	re_path(r'^remove_chart_all/$', views.remove_chart_all),
	re_path(r'^remove_chart/(?P<good_id>[0-9]+)/$', views.remove_chart),
	re_path(r'^add_chart/(?P<good_id>[0-9]+)/(?P<sign>[0-9]+)/$', views.add_chart),
	re_path(r'^update_chart/(?P<good_id>[0-9]+)/$', views.update_chart),
	re_path(r'^view_address/$', views.view_address),
	re_path(r'^add_address/(?P<sign>[0-9]+)/$', views.add_address),
	re_path(r'^delete_address/(?P<address_id>[0-9]+)/(?P<sign>[0-9]+)/$',views.delete_address),
	re_path(r'^update_address/(?P<address_id>[0-9]+)/(?P<sign>[0-9]+)/$', views.update_address),
	re_path(r'^delete_orders/(?P<orders_id>[0-9]+)/(?P<sign>[0-9]+)/$', views.delete_orders),
	re_path(r'^create_order/$', views.create_order),
	re_path(r'^view_order/(?P<orders_id>[0-9]+)/$', views.view_order),
	re_path(r'^view_all_order/$', views.view_all_order),
]+ static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)

goods/models.py
from django.db import models

# Create your models here.
#用户
class User(models.Model):
    username = models.CharField(max_length=50)	#用户名
    password = models.CharField(max_length=64)	#密码
    email = models.EmailField()					#Email

    def __str__(self):
        return self.username

#商品
class Goods(models.Model):
	name = models.CharField(max_length=100)				#商品名称
	price = models.FloatField()							#单价
	picture = models.FileField(upload_to = './static/image/') #图片
	desc = models.TextField()							#描述

	def __str__(self):
		return self.name

#收货地址
class Address(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)					#关联用户id
	address = models.CharField(max_length=50)		#地址
	phone = models.CharField(max_length=15)			#电话
	
	def __str__(self):
		return self.address

#总订单
class Orders(models.Model):
	address = models.ForeignKey(Address,on_delete=models.CASCADE)					#关联送货地址id
	create_time = models.DateTimeField(auto_now=True)		#创建时间
	status = models.BooleanField()							#订单状态

	def __str__(self):
		return self.create_time

#一个订单
class Order(models.Model):
	order =  models.ForeignKey(Orders,on_delete=models.CASCADE)	#关联总订单id
	user = models.ForeignKey(User,on_delete=models.CASCADE)		#关联用户id
	goods = models.ForeignKey(Goods,on_delete=models.CASCADE)	#关联商品id
	count = models.IntegerField()		#数量

goods/forms.py
#coding=utf-8
from django import forms

#定义注册表单模型
class UserForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=100)
    password = forms.CharField(label='密码',widget=forms.PasswordInput())
    email = forms.EmailField(label='电子邮件')

#定义登录表单模型
class LoginForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=100)
    password = forms.CharField(label='密码  ',widget=forms.PasswordInput())

#定义地址表单模型
class AddressForm(forms.Form):
    address = forms.CharField(label='地址',max_length=100)
    phone = forms.CharField(label='电话',max_length=15)

goods/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from goods.models import Goods,Address,Order,Orders,User
from goods.util import Util
from goods.object import Chart_list,Order_list,Orders_list
from goods.forms import UserForm,LoginForm,AddressForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

# 以下是用户管理部分
# 首页(登录)
def index(request):
    uf = LoginForm()
    return render(request,'index.html',{'uf':uf})

#用户登出
def logout(request):
    response = HttpResponseRedirect('/index/') # 登录成功跳转查看商品信息
    del request.session['username']  # 将session 信息写到服务器
    return response

#用户注册
def register(request):
    util = Util()
    if request.method == "POST":                    #判断表单是否提交状态
        uf = UserForm(request.POST)                 #获得表单变量
        if uf.is_valid():                       #判断表单数据是否正确
            #获取表单信息
            username = (request.POST.get('username')).strip()           #获取用户名信息
            password = (request.POST.get('password')).strip()           #获取密码信息
            email = (request.POST.get('email')).strip()     #获取Email信息
            #判断密码是否为空
            if (len(password)!=64):
                uf = UserForm()
                return render(request,'register.html',{'uf':uf,"error":"密码不能小于5位"})
            #查找数据库中是否存在相同用户名
            user_list = User.objects.filter(username=username)
            if user_list:
                #如果存在，报"用户名已经存在！"错误信息并且回到注册页面
                uf = UserForm()
                return render(request,'register.html',{'uf':uf,"error":"用户名已经存在！"})
            else:
                #否则将表单写入数据库
                user = User()
                user.username = username
                user.password = password
                user.email = email
                user.save()
                #返回登录页面
                uf = LoginForm()
                return render(request,'index.html',{'uf':uf})
    else:   #如果不是表单提交状态，显示表单信息
        uf = UserForm()
    return render(request,'register.html',{'uf':uf})

#用户登录
def login_action(request):
    util = Util()
    if request.method == "POST":
        uf = LoginForm(request.POST)
        if uf.is_valid():
            # 寻找名为 "username"和"password"的POST参数，而且如果参数没有提交，返回一个空的字符串。
            username = (request.POST.get('username')).strip()
            password = (request.POST.get('password')).strip()
            #加密password
            #password = util.md5(password)
            # 判断用户名和密码是否准确
            user = User.objects.filter(username = username,password = password)
            if user:
                response = HttpResponseRedirect('/goods_view/') # 登录成功跳转查看商品信息
                request.session['username'] = username    # 将session 信息写到服务器
                return response
            else:
                return render(request,"index.html",{'uf':uf,"error":"用户名或者密码错误"})
    else:
        uf = LoginForm()
    return render(request,'index.html',{'uf':uf})

# 获取用户信息
def user_info(request):
    #检查用户是否登录
    util = Util()
    username = util.check_user(request)
    #如果没有登录，跳转到首页
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入！"})
    else:
        #count为当前购物车中商品的数量
        count = util.cookies_count(request)
        #获取登录用户信息
        user_list = get_object_or_404(User,username=username)
        #获取登录用户收货地址的所有信息
        address_list = Address.objects.filter(user_id=user_list.id)
        return render(request,"view_user.html",{"user": username,"user_info":user_list,"address":address_list,"count":count})

# 修改用户密码
def change_password(request):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        count = util.cookies_count(request)
        #获得当前登录用户的用户信息
        user_info = get_object_or_404(User,username=username)
        #如果是提交表单，获取表单信息，并且进行表单信息验证
        if request.method == "POST":
            #获取旧密码
            oldpassword=request.POST.get("oldpassword", "").strip()
            #获取新密码
            newpassword=request.POST.get("newpassword", "").strip()
            #获取新密码的确认密码
            checkpassword=request.POST.get("checkpassword", "").strip()
            #如果旧密码不正确，报错误信息，不允许修改
            if oldpassword !=user_info.password:
                return render(request,"change_password.html",{"user": username,"error":"旧密码不正确","count":count})
            #如果新密码与旧密码相同，报错误信息，不允许修改
            elif newpassword ==oldpassword:
                return render(request,"change_password.html",{"user": username,"error":"新密码不能与旧密码相同","count":count})
            #如果新密码与新密码的确认密码不匹配，报错误信息，不允许修改
            elif newpassword != checkpassword:
                return render(request,"change_password.html",{"user": username,"error":"确认密码与新密码不匹配","count":count})
            else:
            #否则修改成功
                User.objects.filter(username=username).update(password=newpassword)
                return render(request,"change_password.html",{"user": username,"error":"密码修改成功","count":count})
        #如果不是提交表单，显示修改密码页面
        else:
            return render(request,"change_password.html",{"user": username,"count":count})
# 以下是商品管理部分
#查看商品信息
def goods_view(request):
    util = Util()
    username = util.check_user(request)
    if username =="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        #获得所有商品信息
        good_list = Goods.objects.all()
        #获得购物车中物品数量
        count = util.cookies_count(request)

        #翻页操作
        paginator = Paginator(good_list, 5)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # 若页面不是整数，则交付第一页。
            contacts = paginator.page(1)
        except EmptyPage:
            #如果页面超出范围（例如9999），则交付结果的最后一页。
            contacts = paginator.page(paginator.num_pages)
        return render(request, "goods_view.html", {"user": username, "goodss": contacts,"count":count})

# 商品搜索
def search_name(request):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        #获取查询数据
        count = util.cookies_count(request)
        if request.method == "POST": 
            search_name = (request.POST.get("good", "")).strip()
        if request.method == "GET":
            search_name = (request.GET.get("good", "")).strip()
        #通过objects.filter()方法进行模糊匹配查询，查询结果放入变量good_list
        good_list = Goods.objects.filter(name__icontains=search_name)
        #对查询结果进行分页显示
        paginator = Paginator(good_list, 5)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # 若页面不是整数，则交付第一页。
            contacts = paginator.page(1)
        except EmptyPage:
            # 如果页面超出范围（例如9999），则交付结果的最后一页。
            contacts = paginator.page(paginator.num_pages)
        return render(request, "goods_view.html", {"user": username, "goodss": contacts,"count":count,"goodsname": search_name})

# 查看商品详情
def view_goods(request, good_id):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        count = util.cookies_count(request)
        good = get_object_or_404(Goods, id=good_id)
        return render(request, 'good_details.html', {"user": username,'good': good,"count":count})

# 以下是购物车管理部分
# 放入购物车
def add_chart(request,good_id,sign):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{"error":"请登录后再进入"})
    else:
        #获得商品详情
        good = get_object_or_404(Goods,id=good_id)
        #如果sign=="1"，返回商品列表页面
        if sign=="1":
            response = HttpResponseRedirect('/goods_view/')
        #否则返回商品详情页面
        else:
            response = HttpResponseRedirect('/view_goods/'+good_id)
        #把当前商品添加进购物车，参数为商品编号，值购买商品为个数1，有效时间为一年
        response.set_cookie(str(good.id),1,60*60*24*365)
        return response


# 查看购物车
def view_chart(request):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        #购物车中商品个数
        count = util.cookies_count(request)
        print("++++++++++++")
        print(count)
        #返回所有的cookie内容
        my_chart_list = util.add_chart(request)
        return render(request, "view_chart.html", {"user": username, "goodss": my_chart_list, "count":count})

# 移出购物车
def remove_chart(request,good_id):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        #获取指定编号的商品
        good = get_object_or_404(Goods, id=good_id)
        response = HttpResponseRedirect('/view_chart/')
        #移除购物车
        response.set_cookie(str(good.id),1,0)
        return response

# 修改购物车中商品的数量
def update_chart(request,good_id):
    util = Util()
    username = util.check_user(request)
    if username=="":
        uf = LoginForm()
        return render(request,"index.html",{'uf':uf,"error":"请登录后再进入"})
    else:
        #获取编号为good_id的商品
        good = get_object_or_404(Goods, id=good_id)
        #获取修改的数量
        count = (request.POST.get("count"+good_id, "")).strip()
        #如果数量值<=0,报出错信息
        if int(count)<=0:
            #获得购物车列表信息
            my_chart_list = util.add_chart(request)
            #返回错误信息

goods/templates/add_address.html
{%load static%}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>添加地址</title>
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
	<link href="{%static 'css/my.css'%}" rel="stylesheet">
</head>

<body>

  <div class="container">
    <form class="form-signin" method="post" enctype="multipart/form-data">
      <h2 class="form-signin-heading">添加地址</h2>
	  {% csrf_token %}
      {{uf.as_p}}
        <p style="color:red">{{error}}</p> <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit">提交</button><br>
    </form>

  </div> <!-- /container -->

</body>
</html>

goods/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
      <meta name="description" content="">
      <meta name="author" content="">

      <title>电子商务系统</title>

      <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
  </head>

  <body role="document">
<!-- 导航栏 -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/goods_view/">电子商务系统</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/goods_view/">商品列表</a></li>
			<li class="active"><a href="/view_all_order/">查看所有订单</a></li>
  {% block content %}


  {% endblock %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
        </div>
        <footer class="footer">
          <p>&copy; Company 2017,作者：顾翔</p>
        </footer>

    </div> <!-- /container -->

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </body>

</html>

goods/templates/change_password.html
<script type="text/javascript" src="/static/js/sh256.js"></script>
<script type="text/javascript" >
function SHA256Password()
{
document.forms["myForm"]["oldpassword"].value = SHA256(document.forms["myForm"]["oldpassword"].value);
document.forms["myForm"]["newpassword"].value = SHA256(document.forms["myForm"]["newpassword"].value);
document.forms["myForm"]["checkpassword"].value = SHA256(document.forms["myForm"]["checkpassword"].value);
return true;
}
</script>
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          <form action="/change_password/" method="post" enctype="multipart/form-data" name="myForm" onsubmit="return SHA256Password()">
		  {% csrf_token %}
            <p style="color:red">{{error}}</p> <br>
            旧密码：<input name="oldpassword" type="password" required><br>
            新密码：<input name="newpassword" type="password" required><br>
            确认密码：<input name="checkpassword" type="password" required><br>
            <input type="submit" value="修改">
          </form>
        </div>

      </div>

{% endblock %}

goods/templates/error.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="row" style="margin-top:30px">
        <div class="col-lg-6">
          <div class="input-group">
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->

    <div class="container theme-showcase" role="main">
      <font color="#FF0000">{{error}}</font>
    </div> <!-- /container   glyphicon glyphicon-phone border-style:none; -->
{% endblock %}

goods/templates/good_details.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <!--商品详情-->
      <div class="row" style="margin-top:30px">
        <div class="col-lg-6">
          <div class="input-group">
		  单价：￥{{good.price}}元 <a href="/add_chart/{{good.id}}/2/">放入购物车</a><br>
		  <img src="/{{good.picture}}"><br>
		  {{good.desc}}
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->

    </div> <!-- /container   glyphicon glyphicon-phone border-style:none; -->

{% endblock %}

goods/templates/goods_view.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <!--商品表单-->
      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form" method="post" action="/search_name/">
            <div class="form-group">
			{% csrf_token %}
              <input name="good" type="text" placeholder="名称" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">搜索</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价钱</th>
				<th>查看详情</th>
                <th>放入购物车</th>
              </tr>
            </thead>
            <tbody>
              {% for goods in goodss %}
                <tr>
                  <td id="id">{{ goods.id }}</td>
                  <td id="name">{{ goods.name }}</td>
                  <td id="price">￥{{ goods.price }}</td>
                  <td><a href="/view_goods/{{goods.id}}/">查看</a></td>
                  <td><a href="/add_chart/{{goods.id}}/1/">放入</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
        </div>

      </div>
 <!-- 列表分页器 -->
    <div class="pagination">
      <span class="step-links">
        {% if goodss.has_previous %}
          <a href="?page={{ goodss.previous_page_number }}&good={{goodsname}}">上一页</a>
        {% endif %}
          <span class="current">
            Page {{ goodss.number }} of {{ goodss.paginator.num_pages }}.
          </span>
        {% if goodss.has_next %}
          <a href="?page={{ goodss.next_page_number }}&good={{goodsname}}">下一页</a>
        {% endif %}
      </span>
    </div>
{% endblock %}

goods/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>电子商务系统-登录</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/signin.css" rel="stylesheet"> 
    <!-- Custom styles for this template -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/css/my.css" rel="stylesheet">
	<script type="text/javascript" src="/static/js/sh256.js"></script>
	<script type="text/javascript" >
	function SHA256Password()
	{
	document.forms["myForm"]["password"].value = SHA256(document.forms["myForm"]["password"].value);
	return true;
	}
</script>

  </head>

  <body>

    <div class="container">
      <form class="form-signin" name="myForm" method="post" action="/login_action/" enctype="multipart/form-data" onsubmit="return SHA256Password()">
	  {% csrf_token %}
        <h2 class="form-signin-heading">电子商务系统-登录</h2>
        {{uf.as_p}}
          <p style="color:red">{{error}}</p> <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button><br>
		<a href="\register\">注册</a>
      </form>

    </div> <!-- /container -->

  </body>

</html>

goods/templates/update_address.html
{%load static%}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>修改地址</title>
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
	<link href="{%static 'css/my.css'%}" rel="stylesheet">
</head>

<body>

  <div class="container">
    <form class="form-signin" method="post" enctype="multipart/form-data">
      <h2 class="form-signin-heading">修改地址</h2>
	  {% csrf_token %}
      <p><label for="id_address">地址:</label> <input type="text"  value="{{address.address}}" name="address" id="id_address" size="20" maxlength="100" required /></p>
	  <p><label for="id_phone">电话:</label> <input type="text" value="{{address.phone}}" name="phone" id="id_phone" size="20" maxlength="15" required /></p>
		<p style="color:red">{{error}}</p> <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit">修改</button><br>
    </form>

  </div> <!-- /container -->

</body>
</html>

goods/templates/view_chart.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
    <div class="container theme-showcase" role="main">
	<font color="#FF0000">{{error}}</font>
      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价钱</th>
				        <th>个数</th>
                <th>移除</th>
              </tr>
            </thead>
            <tbody>
			  {% for key in goodss %}
                <tr>
                  <td><a href="/view_goods/{{key.id}}/">{{key.id}}</a></td>
                  <td>{{key.name}}</td>
                  <td>￥{{key.price}}</td>
                  <td><form action="/update_chart/{{key.id}}/" method="post">
				  {% csrf_token %}
				  <input type="number" value="{{key.count}}" style="width:30px;" name="count{{key.id}}" class="vIntegerField" id="id_count" required />
				  <input type="submit" value="修改" /></form></td>
                  <td><a href="/remove_chart/{{key.id}}/">移除</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
		  <form method="get" action="/remove_chart_all/">
		  {% csrf_token %}
		  <input type="submit" value="清除所有">
		  </form>
		  <form method="get" action="/view_address/">
		  {% csrf_token %}
		  <input type="submit" value="生成订单">
		  </form>
        </div>

      </div>
{% endblock %}